#!/bin/bash

for DIR in ./ auxiliary/ auxiliary/help parts/ matlabScripts/
do
   for FILE in `ls $DIR | grep -v "~"` 
   do 
       if [ ! -d $FILE ]
       then
	   Z=`grep $FILE Dependencies/* 2> /dev/null | wc | awk '{print $1}'`
	   echo $Z : ${DIR}/${FILE}
       fi
   done
done
