%Generate NBS icon displayed in GUI
clear all
close all

clr=[0.9,0.9,0.9];

FH=figure('units','centimeters',...
    'position',[3 3 13.5 14],...
    'name','NBS v1.1',...
    'numbertitle','off',...
    'resize','on',...
    'Color',clr);


H(1)=axes('Parent',FH,'units','centimeters',...
    'Color',[1 1 1],...
    'position',[0.5 0.5 2.6 2.1],...
    'box','off',...
    'Visible','off');

H(2)=text(0.52,0.68,'nbs',...
    'Parent',H(1),...
    'FontSize',35,...
    'FontName','Bookman',...
    'FontWeight','bold',...
    'HorizontalAlignment','center',...
    'BackgroundColor',clr);

H(3)=text(0.52,0.26,'CONNECTOME',...
    'Parent',H(1),...
    'FontSize',8,...
    'FontName','Arial Black',...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'BackgroundColor',clr);
F = getframe(H(1));
%save('spc.mat','F'); 
            