#!/bin/bash

# # # # # # # # # # # # # # # # # # 
#
# Convert a phys directory into a physio
# directory and create the physio.log
# file for GE based physio data.
#
#                         Robert C. Welsh
#                         Copyright 2005-2011
#
#
# # # # # # # # # # # # # # # # # #

#
# Main fslCheck function.
#

VERSION="2.0"
VERSIONDATE="2011-10-29"

# Find out where the current command lives and execute some common code.

theFullCommand="$0 $*"
execDIR=`pwd`

# Find out where the current command lives and execute some common code.

theCommand=`which $0`
thisDir=`dirname $theCommand`

thisCommand=`echo $theCommand | awk -F/ '{print $NF}'`

allowedOptions="fM"

# This piece of code all of the spm8Batch scripts will use
. ${thisDir}/auxillary/commonCode_AllScriptsStart

# Validate that we have FSL installed.
. ${thisDir}/auxillary/commonCode_FSL_01

# This is common in-line code for all spm8Batch script to make sure arguments were passed
. ${thisDir}/auxillary/commonCode_checkIfArgsPassed

#
# The actual function.
#

. ${thisDir}/auxillary/parse_arguments

for	(( is=1 ; is<=$nSubjects ; is++ ))
do
    cd ${UMBatchMaster}
    cd ${SUBJDIR}
    cd ${subjects[$is]}
    echo 
    echo ${subjects[$is]}
    echo
    for OBJ in phys raw $fmriPATH
    do
	if [ ! -d ${OBJ} ]
	    then
	    echo Missing ${subjects[$is]}/${OBJ}
	fi
    done
    #
    # Now check func
    #
    if [ -d $fmriPATH ]
	then
	echo -n "  ${subjects[$is]}/$fmriPATH"
	cd $fmriPATH
	for RUN in `ls -l 2> /dev/null | grep drw | grep run_ | awk '{print $NF}'`
	do
	    cd $RUN
	    echo -n " $RUN"
	    for OBJ in run prun aprun raprun arun rarun
	    do
		FILE=`ls  ${OBJ}_??.nii 2> /dev/null | wc | awk '{print $1}'`
		echo -n " $FILE"
	    done
	    cd ../
	done
	echo
	cd ../
    fi
done

echo
echo All done
echo