#!/bin/bash

# # # # # # # # # # # # # # # # # # 
#
# A command to make it easier on the user to segment the 
# SPGR to the standard template.
#
# This command will build a script to run and will also 
# run the script in background.
#
#   e.g.    segSPGR
#
#
#                         Robert C. Welsh
#                         Copyright 2005-2007
#
# segSPGR
#
# # # # # # # # # # # # # # # # # #

#
# Main segSPGR function.
#

VERSION="2.1"
VERSIONDATE="2011-07-30"

# Find out where the current command lives and execute some common code.

theFullCommand="$0 $*"
execDIR=`pwd`

# Find out where the current command lives and execute some common code.

theCommand=`which $0`
thisDir=`dirname $theCommand`

thisCommand=`echo $theCommand | awk -F/ '{print $NF}'`

#allowedOptions="DdfhMnTtUw"
allowedOptions="DdfhMTtUw"

# This piece of code all of the spm8Batch scripts will use
. ${thisDir}/auxillary/commonCode_AllScriptsStart

# This is the common in-line code for the warping steps.
. ${thisDir}/auxillary/commonCode_Seg_01

# This is common in-line code for all spm8Batch script to make sure arguments were passed
. ${thisDir}/auxillary/commonCode_checkIfArgsPassed


#
# The actual function.
#

. ${thisDir}/auxillary/parse_arguments

#

. ${thisDir}/auxillary/superDebugStatus

#
# Ok - let's start displaying things back to the terminal
#

. ${thisDir}/auxillary/shellScriptInfo

#
# Prepare to write the script.
#

# Makes sure they speficied some subjects.
. ${thisDir}/auxillary/checkInputForSubjects

# Write out debug status
. ${thisDir}/auxillary/debugStatus

# Ok, lets do the business.

# Print out the list of subjects that we operate upon.
. ${thisDir}/auxillary/printSubjectsList

# Now start building the automatic scripts.

#
# the following environmental variables are from spm8Batch_Global
#
#    HOSTCOMPUTER     - name of the computer.
#    SCRIPTNAME       - name of the scripts to write.
#    MATLABDIR        - location of the scripts.
#    UMBatchMatcher   - present working directory.
#    FULLSCRIPTNAME   - full path and name of scripts to write.
# 

. ${thisDir}/auxillary/segPart_01

# Now build the list of directories for each subject.

echo "UMImg2Seg    = {..."                               >> ${FULLSCRIPTNAME}.m

declare -i is
declare -i ii

curDIR=`pwd`

for (( is=1 ; is<=$nSubjects ; is++ ))
do

  #
  # Make sure that now the HIRES exists.
  #
  
  TARGETNAME=${UMBatchMaster}/${SUBJDIR}/${subjects[$is]}/${fmriPATH}/${coregPATH}/${HIRESNAME}
  TARGETEXT=${overlayExt}

  . ${thisDir}/auxillary/verifyTargetImage
  
  debugout "HiRes name is : ${TARGETIMG}"    $SuperDebugFLAG
  debugout "- - - - - - - - - - - - - - - -" $SuperDebugFLAG

  echo "'${TARGETIMG}';..."                               >> ${FULLSCRIPTNAME}.m

done

echo "                };"                                 >> ${FULLSCRIPTNAME}.m

echo "    4) finalizing matlab scripts"

cat ${thisDir}/parts/seg_hires_part_2.m                   >> ${FULLSCRIPTNAME}.m

echo "    5) building shell script"
echo

# Now build the shell script command that will get launched into the background.

# Common star to all shell scripts
. ${thisDir}/auxillary/shellScriptStart

# Add the matlab code to the shell script

. ${thisDir}/auxillary/shellScriptMATLABCall

# Finalize the shell script.

. ${thisDir}/auxillary/shellScriptFinalize

# Now launch into the background if desired.

. ${thisDir}/auxillary/shellScriptLaunch

#
# all done.
#
