#!/bin/bash

# # # # # # # # # # # # # # # # # # 
#
# A command to make it easier on the user to smooth their functional 
# images. This command will build a script to run and will also 
# run the script in background.
#
# Robert C. Welsh
# Copyright 2005-2011
#
# smoothfMRI
#
# # # # # # # # # # # # # # # # # #

#
# Main function of smoothfMRI
#

VERSION="2.1"
VERSIONDATE="2011-07-30"

# Find out where the current command lives and execute some common code.

theFullCommand="$0 $*"
execDIR=`pwd`

# Find out where the current command lives and execute some common code.

theCommand=`which $0`
thisDir=`dirname $theCommand`

thisCommand=`echo $theCommand | awk -F/ '{print $NF}'`

allowedOptions="DdfMntUv"

# This piece of code all of the spm8Batch scripts will use
. ${thisDir}/auxillary/commonCode_AllScriptsStart

# This is the common in-line code for the warping steps.
. ${thisDir}/auxillary/commonCode_Smooth_01

# This is common in-line code for all spm8Batch script to make sure arguments were passed
. ${thisDir}/auxillary/commonCode_checkIfArgsPassed

#
# The actual function.
#

. ${thisDir}/auxillary/parse_arguments

#

. ${thisDir}/auxillary/superDebugStatus

# Figure out the gaussian kernal parameters.

if (( $nParam != 0 ))
    then
    if (( $nParam == 1 )) 
	then
	Gx=${params[1]}
	Gy=${params[1]}
	Gz=${params[1]}
    else
	if (( $nParam == 3 ))
	    then
	    Gx=${params[1]}
	    Gy=${params[2]}
	    Gz=${params[3]}
	else
	    echo "Number of numeric parameters needs to be either 1 or 3"
	    exit 0
	fi
    fi
fi

# Make the sandbox if possible.

. ${thisDir}/auxillary/make_sandbox

#
# Ok - let's start displaying things back to the terminal
#

. ${thisDir}/auxillary/shellScriptInfo

#
# Prepare to write the script.
#

# Makes sure they speficied some subjects.
. ${thisDir}/auxillary/checkInputForSubjects

# Write out debug status
. ${thisDir}/auxillary/debugStatus

# Ok, lets do the business.

# Print out the list of subjects that we operate upon.
. ${thisDir}/auxillary/printSubjectsList

# Now start building the automatic scripts.

#
# the following environmental variables are from spm8Batch_Global
#
#    HOSTCOMPUTER     - name of the computer.
#    SCRIPTNAME       - name of the scripts to write.
#    MATLABDIR        - location of the scripts.
#    UMBatchMatcher   - present working directory.
#    FULLSCRIPTNAME   - full path and name of scripts to write.
# 

. ${thisDir}/auxillary/smoothPart_01

# Now build the list of directories for each subject.

. ${thisDir}/auxillary/createDirectoryList

echo "    4) finalizing matlab scripts"

cat ${thisDir}/parts/smooth_part_2.m                         >> ${FULLSCRIPTNAME}.m

echo "    5) building shell script"

# Common start to all shell scripts
. ${thisDir}/auxillary/shellScriptStart

# Now create verify that the sandbox is there.

. ${thisDir}/auxillary/shellScriptCreateSandBox

# Add the matlab code to the shell script

. ${thisDir}/auxillary/shellScriptMATLABCall

# Finalize the shell script.

. ${thisDir}/auxillary/shellScriptFinalize

# Now launch into the background if desired.

. ${thisDir}/auxillary/shellScriptLaunch

#
# all done.
#
