#!/bin/bash

# # # # # # # # # # # # # # # # # # 
#
# A command to make it easier on the user to warp the 
# fmri time-series to the standard template.
#
# This command will build a script to run and will also 
# run the script in background.
#
#   e.g.    warpfMRI
#
#
#                         Robert C. Welsh
#                         Copyright 2005-2011
#
# warpfRMI
#
# # # # # # # # # # # # # # # # # #

#
# Main warpfMRI function.
#

VERSION="2.1"
VERSIONDATE="2011-07-30"

# Find out where the current command lives and execute some common code.

theFullCommand="$0 $*"
execDIR=`pwd`

# Find out where the current command lives and execute some common code.

theCommand=`which $0`
thisDir=`dirname $theCommand`

thisCommand=`echo $theCommand | awk -F/ '{print $NF}'`

allowedOptions="DdfhMntUvwz"

# This piece of code all of the spm8Batch scripts will use
. ${thisDir}/auxillary/commonCode_AllScriptsStart

# This is the common in-line code for the warping steps.
. ${thisDir}/auxillary/commonCode_Warp_01

# This is common in-line code for all spm8Batch script to make sure arguments were passed
. ${thisDir}/auxillary/commonCode_checkIfArgsPassed

#
# The actual function.
#

. ${thisDir}/auxillary/parse_arguments

#

. ${thisDir}/auxillary/superDebugStatus

# Make the sandbox if possible.

. ${thisDir}/auxillary/make_sandbox

#
# Ok - let's start displaying things back to the terminal
#

. ${thisDir}/auxillary/shellScriptInfo

#
# Prepare to write the script.
#

# Makes sure they speficied some subjects.
. ${thisDir}/auxillary/checkInputForSubjects

# Write out debug status
. ${thisDir}/auxillary/debugStatus

# Ok, lets do the business.

# Print out the list of subjects that we operate upon.
. ${thisDir}/auxillary/printSubjectsList

# Now start building the automatic scripts.

#
# the following environmental variables are from spm8Batch_Global
#
#    HOSTCOMPUTER     - name of the computer.
#    SCRIPTNAME       - name of the scripts to write.
#    MATLABDIR        - location of the scripts.
#    UMBatchMatcher   - present working directory.
#    FULLSCRIPTNAME   - full path and name of scripts to write.
# 

. ${thisDir}/auxillary/warpPart_01

# Name of the functional volumes to find.

echo "UMVolumeWild  = '${volumeWILD}';"                   >> ${FULLSCRIPTNAME}.m

# Now build the list of directories for each subject.

. ${thisDir}/auxillary/createDirectoryList

echo " UMHighRes    = {..."                               >> ${FULLSCRIPTNAME}.m
for (( is=1 ; is<=$nSubjects ; is++ ))
do
    
  #
  # Make sure that now the HIRES exists.
  #
    
    TARGETNAME=${UMBatchMaster}/${SUBJDIR}/${subjects[$is]}/${fmriPATH}/${coregPATH}/${HIRESNAME}
    TARGETEXT=${overlayExt}
    
    . ${thisDir}/auxillary/verifyTargetImage
    
    debugout "HiRes name is : ${TARGETIMG}"    $SuperDebugFLAG
    debugout "- - - - - - - - - - - - - - - -" $SuperDebugFLAG
    
    if [ ! -e "${UMBatchMaster}/${SUBJDIR}/${subjects[$is]}/${fmriPATH}/${coregPATH}/${HIRESNAME}_sn.mat" ]
    then
	echo
	echo "MISSING _sn.mat for ${subjects[$is]}"
	echo
	# 
        # remove the sandbox if we made one.
        #
	${thisDir}/auxillary/remove_sandbox ${SANDBOXYES} ${SANDBOXPID}
	exit 1
    fi
    
    echo "'${TARGETIMG}';..."                             >> ${FULLSCRIPTNAME}.m
    
done

echo "                };"                                 >> ${FULLSCRIPTNAME}.m

echo "    4) finalizing matlab scripts"

cat ${thisDir}/parts/warp_fMRI_part_2.m                   >> ${FULLSCRIPTNAME}.m

echo "    5) building shell script"


# Now build the shell script command that will get launched into the background.

# Common start to all shell scripts
. ${thisDir}/auxillary/shellScriptStart

# Now create verify that the sandbox is there.

. ${thisDir}/auxillary/shellScriptCreateSandBox

# Add the matlab code to the shell script

. ${thisDir}/auxillary/shellScriptMATLABCall

# Finalize the shell script.

. ${thisDir}/auxillary/shellScriptFinalize

# Now launch into the background if desired.

. ${thisDir}/auxillary/shellScriptLaunch

#
# all done.
#
