#!/bin/bash
#
# Resample the input image to a new output image using the input space to determine the resampling.
#

InputImage=$1
OutputImage=$2
InputSpace=$3
OutputSpace=$4

INPUTIMAGE=`ls ${InputImage}.nii 2> /dev/null`
OUTPUTIMAGE=`ls ${OutputImage}.nii 2> /dev/null`

INPUTSPACE=`ls ${InputSpace}.nii 2> /dev/null`
OUTPUTSPACE=`ls ${OutputSpace}.nii 2> /dev/null`

if [ -z "${INPUTIMAGE}" ]
then
    echo "Fatal error : Input image ${InputImage} is missing"
    exit 0
fi

if [ ! -z "${OUTPUTIMAGE}" ]
then
    echo "Warning : Output image ${OutputImage} exists, will overwrite"
fi

if [ -z "${INPUTSPACE}" ]
then
    echo "Fatal error : Input space ${InputSpace} is missing"
    exit 0
fi

if [ -z "${OUTPUTSPACE}" ]
then
    echo "Fatal error: Output space ${OutputSpace} is missing"
    exit 0
fi

# Name of a temporary working file

theDate=`date +%y%m%d_%H_%M_%S`

TMPPPID=$PPID 

TMPFILE=`echo ${theDate} $TMPPPID | awk '{printf "tmpWorkFile_%s_%06d",$1,$2}'`

echo Using ${TMPFILE} as a working file

# calculate the transformation matrix

flirt -in ${INPUTSPACE} -ref ${OUTPUTSPACE} -omat ${TMPFILE}.mat

flirt -in ${INPUTIMAGE} -ref ${OUTPUTSPACE} -applyxfm -init ${TMPFILE}.mat -out ${OutputImage}

rm ${TMPFILE}.mat 2> /dev/null

#
# 
#
