Description of LI_normalise
Home > . > LI_normalise.m
LI_normalise
PURPOSE
Spatial (stereotactic) normalization
SYNOPSIS
function params = LI_normalise(VG,VF,matname,VWG,VWF)
DESCRIPTION
 Spatial (stereotactic) normalization
 This is a stripped version to match contrast images
 to the normalized masks. In order not to mess with the global defaults,
 this file was modified to do an affine-only transform, using my
 parameters instead of the global ones. It then saves the mat-file
 and returns instead of writing the file. It is based on
 spm_normalise.m (2.8 John Ashburner 03/03/04), and
 is intended to be used within the LI-toolbox;
 modifications by Marko Wilke, no guarantees!
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
LI This is li.m, the main function of the LI-toolbox:
LI_boot Function to iteratively calculate lateralization indices,
LI_iter function [lis, thrs, voxl, voxr] = LI_iter(A,B,C,out,sm,vw,pre,L,R);