

 


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Experiment Directory
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      

Exp='/net/data4/MAS/';  

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Model Directory
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      

% Model1='/SecondLevel/MSIT/FIR/fixdur/Congruency_noRT/ANOVA_Cells/Tx1_S1';
% Model2='/SecondLevel/MSIT/FIR/fixdur/Congruency_noRT/ANOVA_Cells/Tx2_S1';  
Model1='/SecondLevel/MSIT/FIR/fixdur/Congruency_noRT/Tx1vTx2';
Model2='/SecondLevel/MSIT/FIR/fixdur/TwelveBin/Congruency_noRT/ANOVA_Cells/Tx2_S1';  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Name and path for your output file (leave off the .csv)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

OuputPathTemplate='[Exp]/Output/Level2Extractions/MAS_FIR_SMA';


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Set up the extraction jobs you would like done
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% ExtractionJobs = {...
% 
% %%%%% Go to this folder to get the level 2 SPM.mat %%%%%%      %%%%%%%% and extract using this ROI %%%%%%%%%%%%%%                         
%     '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/SMA_3_5_46_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/SMA_3_5_46_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/SMA_3_5_46_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/SMA_3_5_46_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/SMA_3_5_46_roi.mat' ; ...
%     
%     
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/SMA_3_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/SMA_3_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/SMA_3_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/SMA_3_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/SMA_3_5_46_roi.mat' ; ...
%  
%     '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/LCaudate_n9_5_10_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/LCaudate_n9_5_10_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/LCaudate_n9_5_10_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/LCaudate_n9_5_10_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/LCaudate_n9_5_10_roi.mat' ; ...
%     
%     
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/LCaudate_n9_5_10_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/LCaudate_n9_5_10_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/LCaudate_n9_5_10_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/LCaudate_n9_5_10_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/LCaudate_n9_5_10_roi.mat' ; ...    
%     
%     
%     } ;
%     
    
  ExtractionJobs = {...

%%%%% Go to this folder to get the level 2 SPM.mat %%%%%%      %%%%%%%% and extract using this ROI %%%%%%%%%%%%%%                         
%     '[Exp]/[Model1]/AllTrial_Bin1/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin2/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin3/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin4/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin5/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin11/',                          '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin12/',                          '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
% 
%     
%     '[Exp]/[Model2]/AllTrial_Bin1/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin2/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin3/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin4/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin5/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin11/',                          '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin12/',                          '[Exp]/ROIS/aal_Supp_Motor_Area_L_roi.mat' ; ...
% 
%     '[Exp]/[Model1]/AllTrial_Bin1/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin2/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin3/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin4/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin5/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin11/',                          '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin12/',                          '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
% 
%     
%     '[Exp]/[Model2]/AllTrial_Bin1/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin2/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin3/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin4/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin5/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin11/',                          '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin12/',                          '[Exp]/ROIS/aal_Supp_Motor_Area_R_roi.mat' ; ...
%     
%     
% 
%     '[Exp]/[Model1]/AllTrial_Bin1/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin2/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin3/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin4/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin5/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin11/',                          '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin12/',                          '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
% 
%     
%     '[Exp]/[Model2]/AllTrial_Bin1/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin2/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin3/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin4/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin5/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin11/',                          '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin12/',                          '[Exp]/ROIS/aal_Caudate_L_roi.mat' ; ...
% 
%     '[Exp]/[Model1]/AllTrial_Bin1/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin2/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin3/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin4/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin5/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin11/',                          '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin12/',                          '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
% 
%     
%     '[Exp]/[Model2]/AllTrial_Bin1/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin2/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin3/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin4/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin5/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin11/',                          '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin12/',                          '[Exp]/ROIS/aal_Caudate_R_roi.mat' ; ...
%     
%     
%     '[Exp]/[Model1]/AllTrial_Bin1/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin2/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin3/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin4/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin5/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin11/',                          '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin12/',                          '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
% 
%     
%     '[Exp]/[Model2]/AllTrial_Bin1/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin2/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin3/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin4/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin5/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin11/',                          '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin12/',                          '[Exp]/ROIS/aal_Insula_L_roi.mat' ; ...

    
%     '[Exp]/[Model1]/AllTrial_Bin1/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin2/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin3/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin4/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin5/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin11/',                          '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin12/',                          '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
% 
%     
%     '[Exp]/[Model2]/AllTrial_Bin1/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin2/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin3/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin4/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin5/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin11/',                          '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin12/',                          '[Exp]/ROIS/aal_Occipital_Inf_L_roi.mat' ; ...
% 
%     '[Exp]/[Model1]/AllTrial_Bin1/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin2/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin3/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin4/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin5/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin11/',                          '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin12/',                          '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
% 
%     
%     '[Exp]/[Model2]/AllTrial_Bin1/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin2/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin3/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin4/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin5/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin11/',                          '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin12/',                          '[Exp]/ROIS/aal_Occipital_Inf_R_roi.mat' ; ...


% 
%                       
%     '[Exp]/[Model1]/AllTrial_Bin1/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin2/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin3/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin4/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin5/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin11/',                          '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin12/',                          '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
% 
%     
%     '[Exp]/[Model2]/AllTrial_Bin1/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin2/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin3/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin4/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin5/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin11/',                          '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin12/',                          '[Exp]/ROIS/SMA_n6_2_58_roi.mat' ; ...
%     
%     
%     
%     
%     '[Exp]/[Model1]/AllTrial_Bin1/',                           '[Exp]/ROIS/IPL_n36_n49_49_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin2/',                           '[Exp]/ROIS/IPL_n36_n49_49_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin3/',                           '[Exp]/ROIS/IPL_n36_n49_49_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin4/',                           '[Exp]/ROIS/IPL_n36_n49_49_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin5/',                           '[Exp]/ROIS/IPL_n36_n49_49_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/IPL_n36_n49_49_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/IPL_n36_n49_49_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/IPL_n36_n49_49_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/IPL_n36_n49_49_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/IPL_n36_n49_49_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin11/',                          '[Exp]/ROIS/IPL_n36_n49_49_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin12/',                          '[Exp]/ROIS/IPL_n36_n49_49_roi.mat' ; ...
% 
%     
%     '[Exp]/[Model2]/AllTrial_Bin1/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin2/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin3/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin4/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin5/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin11/',                          '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin12/',                          '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     
%     
%     
%     '[Exp]/[Model1]/AllTrial_Bin1/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin2/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin3/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin4/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin5/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin11/',                          '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin12/',                          '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
% 
%     
%     '[Exp]/[Model2]/AllTrial_Bin1/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin2/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin3/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin4/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin5/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin11/',                          '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin12/',                          '[Exp]/ROIS/Lingual_24_n85_n11_roi.mat' ; ...
%     
%     
%     
%     '[Exp]/[Model1]/AllTrial_Bin1/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin2/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin3/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin4/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin5/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin11/',                          '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin12/',                          '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
% 
%     
%     '[Exp]/[Model2]/AllTrial_Bin1/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin2/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin3/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin4/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin5/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin11/',                          '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin12/',                          '[Exp]/ROIS/PCC_0_n46_28_roi.mat' ; ...
%     
%     
%     '[Exp]/[Model1]/AllTrial_Bin1/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin2/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin3/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin4/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin5/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin11/',                          '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin12/',                          '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
% 
%     
%     '[Exp]/[Model2]/AllTrial_Bin1/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin2/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin3/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin4/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin5/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin11/',                          '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin12/',                          '[Exp]/ROIS/SMA_n6_32_25_roi.mat' ; ...
%     
%     '[Exp]/[Model1]/AllTrial_Bin1/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin2/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin3/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin4/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin5/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin11/',                          '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model1]/AllTrial_Bin12/',                          '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
% 
%     
%     '[Exp]/[Model2]/AllTrial_Bin1/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin2/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin3/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin4/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin5/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin11/',                          '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin12/',                          '[Exp]/ROIS/AnteriorCingulate_from_DFW_roi.mat' ; ...
    %%%/net/data4/MAS/ROIS/AnteriorCingulate_from_DFW_roi.mat
    '[Exp]/[Model1]/AllTrial_Bin1/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    '[Exp]/[Model1]/AllTrial_Bin2/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    '[Exp]/[Model1]/AllTrial_Bin3/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    '[Exp]/[Model1]/AllTrial_Bin4/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    '[Exp]/[Model1]/AllTrial_Bin5/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    '[Exp]/[Model1]/AllTrial_Bin6/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    '[Exp]/[Model1]/AllTrial_Bin7/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    '[Exp]/[Model1]/AllTrial_Bin8/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    '[Exp]/[Model1]/AllTrial_Bin9/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    '[Exp]/[Model1]/AllTrial_Bin10/',                          '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    '[Exp]/[Model1]/AllTrial_Bin11/',                          '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    '[Exp]/[Model1]/AllTrial_Bin12/',                          '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    '[Exp]/[Model1]/AllTrial_Bin13/',                          '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    '[Exp]/[Model1]/AllTrial_Bin14/',                          '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    '[Exp]/[Model1]/AllTrial_Bin15/',                          '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    
%     '[Exp]/[Model2]/AllTrial_Bin1/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin2/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin3/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin4/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin5/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin6/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin7/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin8/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin9/',                           '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin10/',                          '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin11/',                          '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin12/',                          '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ... 
%     '[Exp]/[Model2]/AllTrial_Bin13/',                          '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin14/',                          '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
%     '[Exp]/[Model2]/AllTrial_Bin15/',                          '[Exp]/ROIS/SMA_n6_5_46_roi.mat' ; ...
    } ;



   
addpath /net/dysthymia/slab/users/sripada/repos/matlabScripts/MethodsCore/ExtractionScripts/ExtractROI/
ExtractROI_central