Description of LI
Home > . > LI.m
LI
PURPOSE
This is li.m, the main function of the LI-toolbox:
SYNOPSIS
function [my_li] = LI(out,L,R);
DESCRIPTION
This is li.m, the main function of the LI-toolbox:
a tool to calculate lateralization indices.
Call with li(2) to generate file-output; passing three input
arguments enables file selection for custom left/right masks.
The toolbox can also be scripted by supplying a number of parameters
as a structure to the toolbox; if 'out' is a structure, the following
parameters are necessary:
A    = char array (path or paths to contrast images, one image per line)
B1   = 1 (frontal)
      = 2 (parietal)
      = 3 (temporal)
      = 4 (occipital)
      = 5 (cingulate)
      = 6 (central)
      = 7 (cerebellar)
      = 8 (gray matter)
      = 9 (all standard masks)
      = 10 (no mask)
      = 11 (custom, enables interactive selection [somewhat besides the point of scripting, but...])
      = char array (path or paths to inclusive mask(s), one image per line)
C1   = 1 (standard exclusive mask, midline -5 mm)
      = 2 (standard exclusive mask, midline -10 mm)
      = 3 (no exclusive mask)
      = 4 (custom, enables interactive selection)
      = char array (path or paths to exclusice mask(s), one image per line)
thr1 = 1 (use same threshold for all images)
      = 0 (individual thresholding for all images)
      = -1 (adaptive thresholding
      = -2 (rank-based thresholding)
      = -3 (iterative thresholding, LI-curves)
      = -4 (no threshold)
      = -5 (bootstrapping)
Such a structure may be generated by using
out = struct('A','YOUR_IMAGE','B1',1,'C1',1,'thr1',-5);
upon which LI(out) will analyze YOUR_IMAGE in the frontal lobe (B1 = 1),
excluding the midline (C1 = 1), using the bootstrapping approach (thr1 = -5)
There are also optional arguments which may or may not be supplied: default
values will be used if they are missing. Note that even when scripting, you
can still supply custom left and right mask images.
pre  = 0 (default)
      = 1 (enables preprocessing for custom masks, only necessary if B1 > 10 or char)
thr3 = 0 (default; meaningless if not thr1 = 1; if so, adapt value to your needs)
      = [3 4 4 5] (supplies multiple thresholds if thr1 = 2)
op   = 1 (use optional data clustering; may not be allowed)
      = 2 (use optional variance weighting
      = 3 (use combined clustering and variance weighting; may not be allowed)
      = 4 (default; no optional steps)
vc   = 1 (use total voxel count; may not be allowed)
      = 0 (use total voxel values; default)
ni    = 0 (images not normalized)
      = 1 (images normalized; default)
outfile = string with name of a custom output file (defaults to 'li.txt')
Alternatively, you can use the toolbox in interactive mode; in this case,
you will have to select a contrast image first, preferrably
a spmT_*.image. This *should* be normalized (ideally using the
template-space bounding box and 2x2x2mm); although the contrast is
explicitly matched to the masks if other dimensions (or unnormalized
images) are used, errors will be minimal this way.
Then, any number of standard or custom mask can be selected; custom
ones can be mirrored and binarized to avoid size biases. A mask will
be applied to any number of statistical images (contrasts) chosen above.
This is repeated for all masks and all contrasts.
A mask defining tissue to exclude can also be chosen,
again standard (exclusion of midline structures) or a custom one.
A threshold can be entered for all or for each
contrast image individually, or it can be derived from
the data, using an adaptive (mean intensity[positive Voxels]
or a ranking procedure. No threshold is also possible. An
spmT_image is necessary for the ranking procedure, otherwise
any image can be assessed, also from the non-spm-world (yes,
there is one :). Variance weighting (see below), though, will not work
in this case. Lastly, iterative thresholding is available which
will yield nice lateralization curves as a function of thresholds.
An extension to this is based on a bootstrap approach.
Data clustering refers to the Gaussian smoothing of the contrast
image prior to thresholding, which will remove outliers and
effectively cluster the data. This is an optional step.
Also optionally, variance weighting can be done, taking into acount
the variability of each voxel as assessed during the statistical
analysis and as expressed in the ResMS.img. Both optional steps
can also be combined. They are only recommended if you have reason
to believe that outliers influence your results; they can have a
substantial influence on your results, so be careful here.
The results can be calculated on the voxel values (seems to
make more sense, but may be more vulnerable to outliers)
or on the absolute voxel count.
Finally, results are checked for small numbers of voxel (default
is n=10) or small clusters (default is k=5); an appropriate warning
is given if either is not met, and calculations are aborted if n=0.
The toolbox was developed under and for spm2 and spm5, and it should
work on spm-versions higher than that; it expects
spm_dir/toolbox/LI/data directory with masks and a number of
LI_* helper files, some of which are hacked (lean :) versions
of original spm_functions. I am most indebted to those of you
who really know how to write code (mainly John Ashburner,
Volkmar Glauche, Tom Nichols and many others), so I could steal it.
As it is in parts based on files distributed under the GNU public
license, the same applies to this toolbox and all files coming with it.
Please see the accompanying Readme.txt for more infos.
!USE AT YOUR OWN RISK!
Yours, Marko Wilke
CROSS-REFERENCE INFORMATION
This function calls:
LI This is li.m, the main function of the LI-toolbox:
LI_boot Function to iteratively calculate lateralization indices,
LI_imcalc Perform algebraic functions on images
LI_iter function [lis, thrs, voxl, voxr] = LI_iter(A,B,C,out,sm,vw,pre,L,R);
LI_normalise Spatial (stereotactic) normalization
LI_print This is a stripped-down version of
LI_rank This function is used for ranking t-values in order
LI_reslice Rigid body reslicing of images; modified version, part of the LI-toolbox
LI_write_sn Write Out Warped Images.
This function is called by:
LI This is li.m, the main function of the LI-toolbox:
LI_boot Function to iteratively calculate lateralization indices,
LI_iter function [lis, thrs, voxl, voxr] = LI_iter(A,B,C,out,sm,vw,pre,L,R);
LI_test This is li_test.m, the left-right-helper function of the LI-toolbox: