Description of LI_iter
Home > . > LI_iter.m
LI_iter
PURPOSE
function [lis, thrs, voxl, voxr] = LI_iter(A,B,C,out,sm,vw,pre,L,R);
SYNOPSIS
function [thrs, lis] = LI_iter(A,B,C,out,sm,vw,pre,L,R);
DESCRIPTION
 function [lis, thrs, voxl, voxr] = LI_iter(A,B,C,out,sm,vw,pre,L,R);
 Function to iteratively calculate lateralization indices;
 part of the LI-toolbox: can be used as a standalone function
 and is used via li.m to calculate li-curves.
 Written by Marko Wilke; USE AT YOUR OWN RISK!
CROSS-REFERENCE INFORMATION
This function calls:
LI This is li.m, the main function of the LI-toolbox:
LI_imcalc Perform algebraic functions on images
LI_normalise Spatial (stereotactic) normalization
LI_print This is a stripped-down version of
LI_reslice Rigid body reslicing of images; modified version, part of the LI-toolbox
LI_write_sn Write Out Warped Images.
This function is called by:
LI This is li.m, the main function of the LI-toolbox: