Description of LI_imcalc
Home > . > LI_imcalc.m
LI_imcalc
PURPOSE
Perform algebraic functions on images
SYNOPSIS
function [Q,Vo] = spm_imcalc_ui(P,Q,f,flags,varargin)
DESCRIPTION
 Perform algebraic functions on images
 hacked by Marko to exclude everything unnescessary
 and to !suppress warnings or graphical outputs!, based on
 spm_imcalc_ui 2.7 by John Ashburner, Andrew Holmes 02/09/05
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
LI This is li.m, the main function of the LI-toolbox:
LI_boot Function to iteratively calculate lateralization indices,
LI_iter function [lis, thrs, voxl, voxr] = LI_iter(A,B,C,out,sm,vw,pre,L,R);