Description of LI_reslice
Home > . > LI_mreslice.m
LI_mreslice
PURPOSE
Rigid body reslicing of images in memory, using functionality available in spm_slice_vol; part of the LI-toolbox
SYNOPSIS
res = LI_mreslice(out,in,hold,bin,wo);
DESCRIPTION
Little function to reslice images in memory, based upon functionality
provided by spm_slice_vol as also used by ImCalc;
part of the LI_toolbox distribution;
out  - target image, defining the space to write input image to
in   - image to be resliced
hold - interpolation method; do not use >1 if image contains NaN
bin  - binarize images to res > bin if provided; not done if missing or empty
wo   - additionally write out resliced image? If yes, uses variable 'post' set below
Implementation by Marko Wilke, USE AT YOUR OWN RISK!
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
LI This is li.m, the main function of the LI-toolbox:
LI_boot Function to iteratively calculate lateralization indices,
LI_iter function [lis, thrs, voxl, voxr] = LI_iter(A,B,C,out,sm,vw,pre,L,R);
Generated manually on Wed 7-Dec-2011 16:00:41