Description of LI_write_sn
Home > . > LI_write_sn.m
LI_write_sn
PURPOSE
Write Out Warped Images.
SYNOPSIS
function VO = spm_write_sn(V,prm,flags,extras)
DESCRIPTION
 Write Out Warped Images.
 Another stripped spm-file, to be used within the LI-toolbox;
 it is based on spm_write_sn.m    (2.17 by John Ashburner 03/03/04)
 and was modified to prepend LI_w_ instead of w to allow for
 the safe deletion of generated files; modifications
 by Marko Wilke, USE AT YOUR OWN RISK!
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
LI This is li.m, the main function of the LI-toolbox:
LI_boot Function to iteratively calculate lateralization indices,
LI_iter function [lis, thrs, voxl, voxr] = LI_iter(A,B,C,out,sm,vw,pre,L,R);