#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".

cat .git/`cat .git/HEAD | awk '{print $NF'}` > .spm8BatchVersion
