#!/bin/bash

# # # # # # # # # # # # # # # # # # 
#
# A command to recursively call BET
# and then run fsl fast to determine the best
# bet threshold.
#
#   e.g.   bestBET
#
#
#                         Robert C. Welsh
#                         Copyright 2005-2011
#
#
# # # # # # # # # # # # # # # # # #

#
# Main coregHiRes function.
#

VERSION="2.0"
VERSIONDATE="2011-09-13"

# Find out where the current command lives and execute some common code.

theFullCommand="$0 $*"
execDIR=`pwd`

# Find out where the current command lives and execute some common code.

theCommand=`which $0`
thisDir=`dirname $theCommand`

thisCommand=`echo $theCommand | awk -F/ '{print $NF}'`

#allowedOptions="aDdfhMnOoRrtUw"
allowedOptions="aBDdghMtU"

# This piece of code all of the spm8Batch scripts will use
. ${thisDir}/auxiliary/commonCode_AllScriptsStart

# Validate that we have FSL installed.
. ${thisDir}/auxiliary/commonCode_FSL_01

# This is common in-line code for all spm8Batch script to make sure arguments were passed
. ${thisDir}/auxiliary/commonCode_checkIfArgsPassed

#
# The actual function.
#

. ${thisDir}/auxiliary/parse_arguments

#

. ${thisDir}/auxiliary/superDebugStatus

#
# Ok - let's start displaying things back to the terminal
#

. ${thisDir}/auxiliary/shellScriptInfo

#
# Prepare to write the script.
#

# Makes sure they speficied some subjects.
. ${thisDir}/auxiliary/checkInputForSubjects

# Write out debug status
. ${thisDir}/auxiliary/debugStatus

# Ok, lets do the business.

# Let's check to see if all of the images are where we expect them for each subject.

for (( is=1 ; is<=$nSubjects ; is++ ))
do
    SUBJECTANATOMY=${UMBatchMaster}/${SUBJDIR}/${subjects[$is]}/${anatomyPATH}
    if [ ! -d "${SUBJECTANATOMY}" ]
    then
	echo
	echo "   FATAL ERROR, can't find directory ${SUBJECTANATOMY}"
	echo
	echo
	exit 0
    fi
    if [ ! -e "${SUBJECTANATOMY}/${HIRESNAME}.nii" ]
    then
	echo
	echo "   FATAL ERROR, can't anatomy file ${SUBJECTANATOMY}/${HIRESNAME}.nii"
	echo
	echo
	exit 0
    fi
done

# Print out the list of subjects that we operate upon.
. ${thisDir}/auxiliary/printSubjectsList

# Now start building the automatic scripts.

#
# the following environmental variables are from spm8Batch_Global
#
#    HOSTCOMPUTER     - name of the computer.
#    SCRIPTNAME       - name of the scripts to write.
#    MATLABDIR        - location of the scripts.
#    UMBatchMatcher   - present working directory.
#    FULLSCRIPTNAME   - full path and name of scripts to write.
# 

. ${thisDir}/auxiliary/buildMatlabScripts_01

. ${thisDir}/auxiliary/shellScriptStart

. ${thisDir}/auxiliary/fslCommonScript

echo                                                                                         >> ${FULLSCRIPTNAME}.sh
echo "testFLAG=${testFLAG}"                                                                  >> ${FULLSCRIPTNAME}.sh
echo -n "for SUBJECT in"                                                                     >> ${FULLSCRIPTNAME}.sh
for (( is=1 ; is<=$nSubjects ; is++ ))
do
  echo -n " ${subjects[$is]}"                                                                >> ${FULLSCRIPTNAME}.sh
done
echo                                                                                         >> ${FULLSCRIPTNAME}.sh
echo "do"                                                                                    >> ${FULLSCRIPTNAME}.sh

. ${thisDir}/auxiliary/fslCommonCode_B

echo "    cd $anatomyPATH"                                                                   >> ${FULLSCRIPTNAME}.sh
echo "    mkdir -p BET"                                                                      >> ${FULLSCRIPTNAME}.sh
echo "    cp ${HIRESNAME}.nii BET/"                                                          >> ${FULLSCRIPTNAME}.sh
echo "    cd BET/"                                                                           >> ${FULLSCRIPTNAME}.sh
echo "    echo BETing and fasting"                                                           >> ${FULLSCRIPTNAME}.sh
echo "    ${thisDir}/recursiveBET $HIRESNAME F $BETGRADIENT $BETNAME"                        >> ${FULLSCRIPTNAME}.sh
echo "    echo Couting segment voxels"                                                       >> ${FULLSCRIPTNAME}.sh
echo "    ${thisDir}/auxiliary/countMaskVoxels $BETGRADIENT $BETNAME"                        >> ${FULLSCRIPTNAME}.sh
echo "    echo Finding BET threshold"                                                        >> ${FULLSCRIPTNAME}.sh
echo "    ${thisDir}/BETthreshold"                                                           >> ${FULLSCRIPTNAME}.sh
echo "    logTheUMProcess bestBET ${FULLSCRIPTNAME} $HIRESNAME $BETGRADIENT $BETNAME"        >> ${FULLSCRIPTNAME}.sh

echo "done"                                                                                  >> ${FULLSCRIPTNAME}.sh
echo "echo"                                                                                  >> ${FULLSCRIPTNAME}.sh
echo "echo \" All done\""                                                                    >> ${FULLSCRIPTNAME}.sh
echo "echo"                                                                                  >> ${FULLSCRIPTNAME}.sh

echo                                                                                         >> ${FULLSCRIPTNAME}.sh
echo

echo "Finished building, launching...."

# Finalize the shell script.

. ${thisDir}/auxiliary/shellScriptFinalize

# Now launch into the background if desired.

. ${thisDir}/auxiliary/shellScriptLaunch

#
# all done.
#
