#!/bin/bash

# # # # # # # # # # # # # # # # # # 
#
# A command to make it easier on the user to coregister their 
# T1 overlay to the functional images. 
# This command will build a script to run and will also 
# run the script in background.
#
# To get help on running script, execute script 
# with no command line arguments.
#
# THIS ONLY WORKS WITH NIFTI FILES.
#
#   e.g.    coregOverlay
#
#
#                         Robert C. Welsh
#                         Copyright 2005-2011
#
# coregOverlay
# SPM8 Version, only works with NIFTI and NIFTI_GZ, but not NIFTI_PAIR
#
# # # # # # # # # # # # # # # # # #

# 
# Main coregOverlay function.
#

VERSION="2.1"
VERSIONDATE="2011-07-29"

# Find out where the current command lives and execute some common code.

theFullCommand="$0 $*"
execDIR=`pwd`

# Find out where the current command lives and execute some common code.

theCommand=`which $0`
thisDir=`dirname $theCommand`

thisCommand=`echo $theCommand | awk -F/ '{print $NF}'`

#allowedOptions="aDdfMnOoRrstUvw"
allowedOptions="aBDdfMnOorstUvw"

# This piece of code all of the spm8Batch scripts will use
. ${thisDir}/auxiliary/commonCode_AllScriptsStart

# This is common in-line code for the coregistration steps.
. ${thisDir}/auxiliary/commonCode_CoReg_01

# This is common in-line code for all spm8Batch script to make sure arguments were passed
. ${thisDir}/auxiliary/commonCode_checkIfArgsPassed

#
# The actual function.
#

. ${thisDir}/auxiliary/parse_arguments

# 

. ${thisDir}/auxiliary/superDebugStatus

#
# Ok - let's start displaying things back to the terminal
#

. ${thisDir}/auxiliary/shellScriptInfo

#
# Prepare to write the script.
#

# Makes sure they speficied some subjects.
. ${thisDir}/auxiliary/checkInputForSubjects

# Write out debug status
. ${thisDir}/auxiliary/debugStatus

# Ok, lets do the business.

# Write out the status of the reslicing flag.
. ${thisDir}/auxiliary/coregResliceStatusMsg

# Print out the list of subjects that we operate upon.
. ${thisDir}/auxiliary/printSubjectsList

# Now start building the automatic scripts.

#
# the following environmental variables are from spm8Batch_Global
#
#    HOSTCOMPUTER     - name of the computer.
#    SCRIPTNAME       - name of the scripts to write.
#    MATLABDIR        - location of the scripts.
#    UMBatchMatcher   - present working directory.
#    FULLSCRIPTNAME   - full path and name of scripts to write.
# 

. ${thisDir}/auxiliary/coregPart_01

# Now build the list of directories for each subject.

echo "UMImgPairs    = {..."                                  >> ${FULLSCRIPTNAME}.m

declare -i is
declare -i ii

curDIR=`pwd`

for (( is=1 ; is<=$nSubjects ; is++ ))
do
    cd ${UMBatchMaster}/${SUBJDIR}/${subjects[$is]}/
  #
  # create the coregistation directory.
  #
    
    debugout "- - - - - - - - - - - - - -"        $SuperDebugFLAG
    debugout "mkdir -p ${fmriPATH}/${coregPATH}/" $SuperDebugFLAG
    debugout "- - - - - - - - - - - - - -"        $SuperDebugFLAG
    mkdir -p ${fmriPATH}/${coregPATH}/
    debugout "- - - - - - - - - - - - - -"        $SuperDebugFLAG
    debugout "cd ${fmriPATH}/${coregPATH}/"       $SuperDebugFLAG
    debugout "- - - - - - - - - - - - - -"        $SuperDebugFLAG
    
    . ${thisDir}/auxiliary/coregDirectoryErrorCheck

    # The overlay is becoming the source,

    SOURCENAME=${overlayNAME}
    SOURCEEXT=${overlayExt}
    
    # find and move it.
    . ${thisDir}/auxiliary/coregFindSourceAndMove

    # Now find the target.

    nVOLS=`ls -1 ${UMBatchMaster}/${SUBJDIR}/${subjects[$is]}/${fmriPATH}/${GENERICRUNDIR}*/${subPATH}/${volumeWILD}*.nii* 2> /dev/null | wc | awk '{print $1}'`
    debugout "# of fMRI Volumes of name '${volumeWILD}' is ${nVOLS}" $SuperDebugFLAG
    if (( $nVOLS == 0 ))
    then
	echo 
	echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * "
	echo
	echo "There are no fmri images specified, please fix and start again. Subject : ${subjects[$is]}"
	echo 
	echo "* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * "
	echo
	exit 1
    fi
    #
    # Find the first run to coregister to. It can be either nii or nii_gz
    #
    TARGETIMG=`ls -1 ${UMBatchMaster}/${SUBJDIR}/${subjects[$is]}/${fmriPATH}/${GENERICRUNDIR}*/${subPATH}/${volumeWILD}*.nii* | head -1`
    debugout "Coreging '${destSOURCENAME}' to '${TARGETIMG}'" $SuperDebugFLAG
    debugout "- - - - - - - - - - - - - -" $SuperDebugFLAG
    echo "{ '${SOURCEIMG}','${TARGETIMG}' };..."                 >> ${FULLSCRIPTNAME}.m
done

echo "                };"                                        >> ${FULLSCRIPTNAME}.m

# Get the other images into the matlab script

. ${thisDir}/auxiliary/coregPrepOtherImages

# Wrap up the writing of the matlab script.

. ${thisDir}/auxiliary/coregPart_02

cd $curDIR

# Now build the shell script command that will get launched into the background.

# Common start to all shell scripts
. ${thisDir}/auxiliary/shellScriptStart

# Add the matlab code to the shell script

. ${thisDir}/auxiliary/shellScriptMATLABCall

# Finalize the shell script.

. ${thisDir}/auxiliary/shellScriptFinalize

# Now launch into the background if desired.

. ${thisDir}/auxiliary/shellScriptLaunch

#
# all done.
#
