#!/bin/bash
# # # # # # # # # # # # # # # # # # 
#
# 
#
# Robert C. Welsh
# Copyright 2006-2011
#
#
# # # # # # # # # # # # # # # # # # 

# We need to know where we live.

theCommand=`which $0`
thisDir=`dirname $theCommand`

CURPID=$$

RUNDIR=$1
VOLUME=$2
N=$3

tmpfile=mcflirt_${CURPID}

if [ ! -d "${RUNDIR}" ]
then
    echo "Missing run directory : $RUNDIR"
    exit 65
fi

cd ${RUNDIR}

VOLNII=`ls ${VOLUME}*.nii 2> /dev/null`

if [ -z "${VOLNII}" ]
then
    echo "Missing nifti file in $RUNDIR for $VOLUME"
    exit 65
fi

rm -r ${tmpfile}

mkdir -p ${tmpfile}

cd ${tmpfile}

FSLOUTPUTTYPE=NIFTI_PAIR

fslsplit ../${VOLNII} ${tmpfile}_ -t

REFNO=`echo $N | awk '{printf "%04d",$1}'`

REFFILE=${tmpfile}_${REFNO}

if [ ! -e ${REFFILE}.img ]
then
    echo "Conversion failed, or coudn't find ${REFFILE}.img"
    . ${thisDir}/auxiliary/exit_w_removal
fi

mv ${REFFILE}.img ../
mv ${REFFILE}.hdr ../

cd ../

rm -r ${tmpfile}

FSLOUTPUTTYPE=NIFTI

fslmerge -t ../realignRefVolume ${REFFILE}

rm ${REFFILE}.img
rm ${REFFILE}.hdr

exit 0

#
# all done
#
