#!/bin/bash

# # # # # # # # # # # # # # # # # # 
#
# A command to make it easier on the user to warp the 
# fmri time-series to the standard template.
#
# This command will build a script to run and will also 
# run the script in background.
#
#   e.g.   spm8Batch
#
#
#                         Robert C. Welsh
#                         Copyright 2005-2012
#
# spm8Batch
#
# # # # # # # # # # # # # # # # # #

#
# Main spm8Batch function.
#

VERSION="2.1"
VERSIONDATE="2012-08-27"

# Find out where the current command lives and execute some common code.

theFullCommand="$0 $*"
execDIR=`pwd`

# Find out where the current command lives and execute some common code.

theCommand=`which $0`
thisDir=`dirname $theCommand`

thisCommand=`echo $theCommand | awk -F/ '{print $NF}'`

# We only will print out the help and ignore everything!

. ${thisDir}/auxiliary/help/${thisCommand}_Help

exit 0

#
# all done.
#