#!/bin/bash

# # # # # # # # # # # # # # # # # # 
#
# A command to make it easier on the user to warp the 
# SPGR to the standard template.
#
# This command will build a script to run and will also 
# run the script in background.
#
#   e.g.    vbm8HiRes
#
#
#                         Robert C. Welsh
#                         Copyright 2005-2011
#
# warpHiRes
#
# # # # # # # # # # # # # # # # # #

#
# Main vbm8HiRes function.
#

VERSION="1.0"
VERSIONDATE="2012-03-05"

# Find out where the current command lives and execute some common code.

theFullCommand="$0 $*"
execDIR=`pwd`

# Find out where the current command lives and execute some common code.

theCommand=`which $0`
thisDir=`dirname $theCommand`

thisCommand=`echo $theCommand | awk -F/ '{print $NF}'`

allowedOptions="aDdhIMntUwz"

# This piece of code all of the spm8Batch scripts will use
. ${thisDir}/auxiliary/commonCode_AllScriptsStart

# This is the common in-line code for the warping steps.
. ${thisDir}/auxiliary/commonCode_VBM8_01

# This is common in-line code for all spm8Batch script to make sure arguments were passed
. ${thisDir}/auxiliary/commonCode_checkIfArgsPassed

#
# The actual function.
#

. ${thisDir}/auxiliary/parse_arguments

#

. ${thisDir}/auxiliary/superDebugStatus

#
# Ok - let's start displaying things back to the terminal
#

. ${thisDir}/auxiliary/shellScriptInfo

#
# Prepare to write the script.
#

# Makes sure they speficied some subjects.
. ${thisDir}/auxiliary/checkInputForSubjects

# Write out debug status
. ${thisDir}/auxiliary/debugStatus

# Ok, lets do the business.

# Print out the list of subjects that we operate upon.
. ${thisDir}/auxiliary/printSubjectsList

# Now start building the automatic scripts.

#
# the following environmental variables are from spm8Batch_Global
#
#    HOSTCOMPUTER     - name of the computer.
#    SCRIPTNAME       - name of the scripts to write.
#    MATLABDIR        - location of the scripts.
#    UMBatchMatcher   - present working directory.
#    FULLSCRIPTNAME   - full path and name of scripts to write.
# 

. ${thisDir}/auxiliary/vbm8_part_01

# Now build the list of directories for each subject.

echo "UMImg2Warp    = {..."                               >> ${FULLSCRIPTNAME}.m

declare -i is
declare -i ii

curDIR=`pwd`

for (( is=1 ; is<=$nSubjects ; is++ ))
do
    
    cd ${UMBatchMaster}/${SUBJDIR}/${subjects[$is]}/
  #
  # create the vbm8 directory.
  #
    
    debugout "- - - - - - - - - - - - - -"        $SuperDebugFLAG
    debugout "mkdir -p ${fmriPATH}/${coregPATH}/" $SuperDebugFLAG
    debugout "- - - - - - - - - - - - - -"        $SuperDebugFLAG
    mkdir -p ${fmriPATH}/${coregPATH}/
    debugout "- - - - - - - - - - - - - -"        $SuperDebugFLAG
    debugout "cd ${fmriPATH}/${coregPATH}/"       $SuperDebugFLAG
    debugout "- - - - - - - - - - - - - -"        $SuperDebugFLAG
    
    . ${thisDir}/auxiliary/coregDirectoryErrorCheck

    # The hires is becoming the source,
    
    SOURCENAME=${HIRESNAME}
    SOURCEEXT=${HIRESEXT}
    
    debugout "HiRes name is : ${SOURCENAME}"   $SuperDebugFLAG
    debugout "- - - - - - - - - - - - - - - -" $SuperDebugFLAG

    . ${thisDir}/auxiliary/vbm8FindSourceAndMove

  echo "'${SOURCEIMG}';..."                               >> ${FULLSCRIPTNAME}.m

done

echo "                };"                                 >> ${FULLSCRIPTNAME}.m

echo

echo "    4) finalizing matlab scripts"

cat ${thisDir}/parts/vbm8_part_02.m                       >> ${FULLSCRIPTNAME}.m

echo "    5) building shell script"
echo

# Now build the shell script command that will get launched into the background.

# Common star to all shell scripts
. ${thisDir}/auxiliary/shellScriptStart

# Add the matlab code to the shell script

. ${thisDir}/auxiliary/shellScriptMATLABCall

# Finalize the shell script.

. ${thisDir}/auxiliary/shellScriptFinalize

# Now launch into the background if desired.

. ${thisDir}/auxiliary/shellScriptLaunch

#
# all done.
#
